### ISSUE TITLE
无法编译成功

### ISSUE THREAD

**Issue by galaxymy** [MutoMagic/xstream#2]
xstream.cs(29,9,29,21): error CS0246: The type or namespace name 'VideoDisplay' could not be found (are you missing a using directive or an assembly reference?)

 VideoDisplay[] _displays;
 VideoDisplay PrimaryDisplay => _displays[0];

还有下面的 GetWindowDisplayIndex    GetDisplayBounds
是需要调用 SDL里面的函数吗

----
还有xstream 可以调fps吗 我主要想找个能降低fps的输出的 串流方案

**Comment by MutoMagic** [comment]
串流fps那个 目前连OpenXbox那边都没给出完整的解答 我也是根据它的py项目进行猜测的
至于编译问题 图形输出这块 我正在重置 因为本地硬盘问题丢失了一些代码

**Comment by galaxymy** [comment]
谢谢回复  我也是在他那个基础上调试， 但fps一直是60 和 720p   怎么调maxrate/fps/分辨率  都无法降低

你那边有一些改变吗？如果有点希望 我也在调调  没有办法我就放弃了  感觉是他跟新握手方式了 视频开始的时候有些不识别的数据

现在主要是cpu太高， 家里优化可以降低50%， 但主要问题fps 60 太高 需要30

还有你这个 input 是绑定现有连接的 手柄做输出， 还是有用键盘 模拟 因为编译问题，也没详细了解

**Comment by MutoMagic** [comment]
input 这部分功能并不完善 两个都在开发中 我会优先支持键盘模拟

fps相关部分请参考：
https://github.com/OpenXbox/xbox-smartglass-nano-python/issues/7
对于值的猜测：
https://github.com/MutoMagic/xstream/blob/master/xstream/Program.cs#L174
！猜测内容尚未经过测试，无法确保是否可行。
